Repository immersve/immersve-docs, pull requests merged in 2023-08, with the labels that each got.

#109 update proxy prod address
  docs/contracts/payment-protocol.md
Labels: ditto

#111 Add cardProgramId to create card endpoint
  openapi/endpoints/cards/card-order.yaml
  openapi/endpoints/cards/models/card-order-request.yaml
Labels: charmander

#112 Use the correct word in url field description
  openapi/endpoints/login/models/challenge-request.yaml
Labels: charmander

#113 Submit KYC Statement Endpoint
  docs/redirects/kyc-custodial.mdx
  docs/redirects/upload-a-kyc-resource.mdx
  openapi/endpoints/kyc/models/ADDRESS.yaml
  openapi/endpoints/kyc/models/DOB.yaml
  openapi/endpoints/kyc/models/FULL_NAME.yaml
  openapi/endpoints/kyc/models/OTHER.yaml
  openapi/endpoints/kyc/models/SELF_IMAGE.yaml
  openapi/endpoints/kyc/models/claims.yaml
  openapi/endpoints/kyc/models/evidence.yaml
  openapi/endpoints/kyc/models/kyc-partner-statement-request.yaml
  openapi/endpoints/kyc/models/upload-kyc-resource-request.yaml
  openapi/endpoints/kyc/models/upload-kyc-resource-response.yaml
  openapi/endpoints/kyc/models/upload-props.yaml
  openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
  openapi/endpoints/kyc/upload-kyc-resource.yaml
  openapi/immersve.yaml
Labels: spoink

#114 Add suburb and town to KYC address spec
  openapi/endpoints/kyc/models/ADDRESS.yaml
Labels: spoink

#115 Add list funding sources endpoint
  openapi/endpoints/funding-sources/funding-sources-list.yaml
  openapi/endpoints/funding-sources/models/funding-source.yaml
  openapi/endpoints/funding-sources/models/list-funding-sources-result.yaml
  openapi/immersve.yaml
Labels: ditto

#117 Remove custodial api references
  docs/redirects/accounts-custodial.mdx
  docs/redirects/activate-card-custodial.mdx
  docs/redirects/block-card-custodial.mdx
  docs/redirects/cancel-account-custodial.mdx
  docs/redirects/cards-custodial.mdx
  docs/redirects/close-card-custodial.mdx
  docs/redirects/create-account-custodial.mdx
  docs/redirects/create-card-custodial.mdx
  docs/redirects/get-account-custodial.mdx
  docs/redirects/get-card-custodial.mdx
  docs/redirects/get-secure-card-custodial.mdx
  docs/redirects/set-pin-card-custodial.mdx
  docs/redirects/unblock-card-custodial.mdx
  docs/redirects/update-account-custodial.mdx
  openapi/immersve.yaml
Labels: ditto

#118 list accounts endpoint documentation
  openapi/endpoints/accounts/accounts-list.yaml
  openapi/endpoints/accounts/models/account.yaml
  openapi/endpoints/accounts/models/list-accounts-response.yaml
  openapi/immersve.yaml
Labels: charmander
