Repository immersve/immersve-docs, pull requests merged in 2023-09, with the labels that each got.

#116 Add claim funding source api
  openapi/endpoints/funding-source/create-funding-source.yaml
  openapi/endpoints/funding-source/models/create-funding-source-eoa.yaml
  openapi/endpoints/funding-source/models/create-funding-source-erc-1271.yaml
  openapi/immersve.yaml
Labels: charmander

#128 📝 Add flag for cardholder account creation during SIWE login
  openapi/endpoints/login/models/login-request.yaml
  openapi/endpoints/login/models/login-response.yaml
Labels: spoink

#133 Chore(currencyConversion) - Remove minor units flag
  openapi/endpoints/currency/currency-convert.yaml
  openapi/endpoints/currency/models/currency-conversion.yaml
Labels: ditto

#134 Chore(transactions & cards) - Remove minor units flag
  openapi/endpoints/cards/card-get.yaml
  openapi/endpoints/cards/cards-list.yaml
  openapi/endpoints/cards/models/get-card.yaml
  openapi/endpoints/transactions/models/transaction.yaml
  openapi/endpoints/transactions/transaction-get.yaml
  openapi/endpoints/transactions/transactions-list.yaml
  openapi/immersve.yaml
Labels: ditto

#137 📝 Add KYC requirements to Spending Prerequisites Endpoint
  openapi/endpoints/prerequisites/models/get-spending-prerequisite-response.yaml
  openapi/endpoints/prerequisites/spending-prerequisites.yaml
  openapi/models/kyc-params.yaml
Labels: spoink

#138 Retrieve KYC statement endpoint
  openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
  openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml
  openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
  openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
  openapi/immersve.yaml
Labels: spoink

#139 Monetary Units Guide
  docs/guides/monetary-units.md
Labels: ditto

#140 Chore - Error Format - update 400 and 403 to new format
  openapi/endpoints/accounts/accounts-create.yaml
  openapi/endpoints/accounts/accounts-list.yaml
  openapi/endpoints/asset-activities/asset-activities-get.yaml
  openapi/endpoints/asset-activities/asset-activities-list.yaml
  openapi/endpoints/cards/card-get.yaml
  openapi/endpoints/cards/cards-list.yaml
  openapi/endpoints/cards/create-card-async.yaml
  openapi/endpoints/funding-sources/list-funding-sources.yaml
  openapi/endpoints/funding-sources/register-funding-source.yaml
  openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
  openapi/endpoints/kyc/submit-partner-kyc-statement.yaml
  openapi/endpoints/prerequisites/spending-prerequisites.yaml
  openapi/models/api-error-400.yaml
  openapi/models/api-error-403.yaml
  openapi/models/api-error.yaml
Labels: ditto

#142 Chore - error formatting - Make 400 use uniform and add errors to endpoints where missing
  openapi/endpoints/accounts/accounts-create.yaml
  openapi/endpoints/asset-activities/asset-activities-get.yaml
  openapi/endpoints/asset-activities/asset-activities-list.yaml
  openapi/endpoints/cards/card-cancel.yaml
  openapi/endpoints/cards/card-get.yaml
  openapi/endpoints/cards/card-pan-token.yaml
  openapi/endpoints/cards/cards-list.yaml
  openapi/endpoints/cards/create-card-async.yaml
  openapi/endpoints/currency/currency-convert.yaml
  openapi/endpoints/funding-sources/list-funding-sources.yaml
  openapi/endpoints/login/siwe-generate-challenge.yaml
  openapi/endpoints/login/siwe-login.yaml
  openapi/endpoints/prerequisites/spending-prerequisites.yaml
  openapi/endpoints/simulator/authorize.yaml
  openapi/endpoints/simulator/clear.yaml
  openapi/endpoints/simulator/reverse.yaml
  openapi/endpoints/transactions/transaction-get.yaml
  openapi/endpoints/transactions/transactions-list.yaml
Labels: ditto

#141 Chore - Error codes - 403
  openapi/endpoints/accounts/accounts-create.yaml
  openapi/endpoints/accounts/accounts-list.yaml
  openapi/endpoints/asset-activities/asset-activities-get.yaml
  openapi/endpoints/asset-activities/asset-activities-list.yaml
  openapi/endpoints/cards/cards-list.yaml
  openapi/endpoints/cards/create-card-async.yaml
  openapi/endpoints/funding-sources/list-funding-sources.yaml
  openapi/endpoints/funding-sources/register-funding-source.yaml
  openapi/endpoints/kyc/retrieve-partner-kyc-statement.yaml
  openapi/endpoints/prerequisites/spending-prerequisites.yaml
Labels: ditto
