Repository immersve/immersve-docs, pull requests merged in 2024-05, with the labels that each got.

#267 feat(docs): Add signup, login init and login complete
  imsv-docs-astro/src/content/docs/guides/authentication.mdoc
  imsv-docs-astro/src/redirects.yml
  imsv-docs-docusaurus/openapi/endpoints/client-application/client-application-update-origins.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/login-complete.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/login-init.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/models/login-complete-request.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/models/login-complete-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/models/login-init-request.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/models/login-init-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/models/signup-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/signup.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/siwe-generate-challenge.yaml
  imsv-docs-docusaurus/openapi/endpoints/login/siwe-login.yaml
  imsv-docs-docusaurus/openapi/immersve.yaml
  scripts/redirect-lint.sh
Labels: charmander

#253 feat(docs): Add region docs
  imsv-docs-astro/astro.config.mjs
  imsv-docs-astro/src/content/docs/guides/regions.mdoc
Labels: spoink

#280 feat(kyc): Add region to KYC statement endpoints
  imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
  imsv-docs-docusaurus/openapi/endpoints/kyc/models/retrieve-kyc-statement-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/kyc/models/submit-kyc-statement-request.yaml
Labels: spoink

#289 feat(region): Add Australia to supported regions in public docs
  imsv-docs-astro/src/content/docs/guides/regions.mdoc
Labels: spoink

#308 Remove erroneous properties from dob claim for partner submitted statements
  imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
Labels: bug, spoink

#310 Add 1 wallet 1 region warnings. Clarifying test docs for ICKYC
  .editorconfig
  imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
  imsv-docs-astro/src/content/docs/guides/kyc/introduction.mdoc
  imsv-docs-astro/src/content/docs/guides/kyc/partner-conducted-kyc.mdoc
Labels: spoink
