Repository immersve/immersve-docs, pull requests merged in 2025-03, with the labels that each got.

#625 Update 400 error
  imsv-docs-docusaurus/openapi/models/api-error-400.yaml
Labels: charmander

#624 Add residential addresses endpoints to the API reference and update IC KYC
  imsv-docs-astro/src/content/docs/guides/kyc/immersve-conducted-kyc.mdoc
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/get-residential-addresses.yaml
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/residential-addresses-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/structured-address-request.yaml
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/structured-address-response.yaml
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/models/unstructured-address-request.yaml
  imsv-docs-docusaurus/openapi/endpoints/residential-addresses/submit-residential-addresses.yaml
  imsv-docs-docusaurus/openapi/immersve.yaml
Labels: spoink

#630 Add mode to funding channel
  imsv-docs-docusaurus/openapi/endpoints/funding-channel/models/funding-channel.yaml
Labels: ditto
